version: '3'

services:
  wechat-notifier:
    build: .
    container_name: wechat-notifier
    restart: unless-stopped
    ports:
      - "12121:12121"   # 服务端口
      - "9229:9229"     # Node.js 调试端口
    volumes:
      - ./database:/app/database
    environment:
      - PORT=12121
      - NODE_ENV=development
      - DB_PATH=/app/database/notifier.db
      - ENCRYPTION_KEY=change-this-to-a-random-32-character-string
      - WECHAT_API_BASE=https://qyapi.weixin.qq.com
    command: npm run dev
